version: '3.8'
services:
  docs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/*/node_modules
      - /app/apps/*/node_modules
    environment:
      - NODE_ENV=development
