version: '3.8'
services:
  docs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/button/node_modules
      - /app/packages/code-block/node_modules
      - /app/apps/docs/node_modules
    environment:
      - NODE_ENV=development
