version: '3.8'

services:
  docs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container port 3000 to host
    volumes:
      - .:/app # Mount the entire project
      - /app/node_modules # Exclude node_modules from host
    environment:
      NODE_ENV: development
