version: '3.8'

services:
  playground:
    build: .
    ports:
      - "3003:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - playground:/app/.next
    environment:
      - NODE_ENV=development

volumes:
  playground:



