name: Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [button, split-text, cli]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Check if version changed
        id: check_version
        run: |
          PACKAGE_PATH="packages/${{ matrix.package }}/package.json"
          CURRENT_VERSION=$(node -p "require('./${PACKAGE_PATH}').version")
          PUBLISHED_VERSION=$(npm view @open-react-hub/${{ matrix.package }} version 2>/dev/null || echo "0.0.0")
          if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.check_version.outputs.version_changed == 'true'
        run: npm ci

      - name: Publish package
        if: steps.check_version.outputs.version_changed == 'true'
        run: npm run publish-${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

